#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JailManagement
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Employee")]
	public partial class JailManagementDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertComplain(Complain instance);
    partial void UpdateComplain(Complain instance);
    partial void DeleteComplain(Complain instance);
    partial void InsertCriminal(Criminal instance);
    partial void UpdateCriminal(Criminal instance);
    partial void DeleteCriminal(Criminal instance);
    partial void InsertPost_Mortem_Report(Post_Mortem_Report instance);
    partial void UpdatePost_Mortem_Report(Post_Mortem_Report instance);
    partial void DeletePost_Mortem_Report(Post_Mortem_Report instance);
    partial void InsertEmployee(Employee instance);
    partial void UpdateEmployee(Employee instance);
    partial void DeleteEmployee(Employee instance);
    #endregion
		
		public JailManagementDataContext() : 
				base(global::JailManagement.Properties.Settings.Default.EmployeeConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public JailManagementDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public JailManagementDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public JailManagementDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public JailManagementDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Complain> Complains
		{
			get
			{
				return this.GetTable<Complain>();
			}
		}
		
		public System.Data.Linq.Table<Criminal> Criminals
		{
			get
			{
				return this.GetTable<Criminal>();
			}
		}
		
		public System.Data.Linq.Table<Post_Mortem_Report> Post_Mortem_Reports
		{
			get
			{
				return this.GetTable<Post_Mortem_Report>();
			}
		}
		
		public System.Data.Linq.Table<Employee> Employees
		{
			get
			{
				return this.GetTable<Employee>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Complain")]
	public partial class Complain : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Complain_id;
		
		private string _Full_Name;
		
		private string _National_id;
		
		private System.Nullable<System.DateTime> _Date_of_Birth;
		
		private string _Gender;
		
		private string _Address;
		
		private string _Nationality;
		
		private string _Complain_Against;
		
		private string _Suspect_Id;
		
		private string _Details;
		
		private System.Nullable<System.DateTime> _Complain_date;
		
		private System.Nullable<System.DateTime> _Creation_Date;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnComplain_idChanging(string value);
    partial void OnComplain_idChanged();
    partial void OnFull_NameChanging(string value);
    partial void OnFull_NameChanged();
    partial void OnNational_idChanging(string value);
    partial void OnNational_idChanged();
    partial void OnDate_of_BirthChanging(System.Nullable<System.DateTime> value);
    partial void OnDate_of_BirthChanged();
    partial void OnGenderChanging(string value);
    partial void OnGenderChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnNationalityChanging(string value);
    partial void OnNationalityChanged();
    partial void OnComplain_AgainstChanging(string value);
    partial void OnComplain_AgainstChanged();
    partial void OnSuspect_IdChanging(string value);
    partial void OnSuspect_IdChanged();
    partial void OnDetailsChanging(string value);
    partial void OnDetailsChanged();
    partial void OnComplain_dateChanging(System.Nullable<System.DateTime> value);
    partial void OnComplain_dateChanged();
    partial void OnCreation_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreation_DateChanged();
    #endregion
		
		/*public Complain()
		{
			OnCreated();
		}*/
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Complain_id", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Complain_id
		{
			get
			{
				return this._Complain_id;
			}
			set
			{
				if ((this._Complain_id != value))
				{
					this.OnComplain_idChanging(value);
					this.SendPropertyChanging();
					this._Complain_id = value;
					this.SendPropertyChanged("Complain_id");
					this.OnComplain_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Full_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Full_Name
		{
			get
			{
				return this._Full_Name;
			}
			set
			{
				if ((this._Full_Name != value))
				{
					this.OnFull_NameChanging(value);
					this.SendPropertyChanging();
					this._Full_Name = value;
					this.SendPropertyChanged("Full_Name");
					this.OnFull_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_National_id", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string National_id
		{
			get
			{
				return this._National_id;
			}
			set
			{
				if ((this._National_id != value))
				{
					this.OnNational_idChanging(value);
					this.SendPropertyChanging();
					this._National_id = value;
					this.SendPropertyChanged("National_id");
					this.OnNational_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date_of_Birth", DbType="DateTime")]
		public System.Nullable<System.DateTime> Date_of_Birth
		{
			get
			{
				return this._Date_of_Birth;
			}
			set
			{
				if ((this._Date_of_Birth != value))
				{
					this.OnDate_of_BirthChanging(value);
					this.SendPropertyChanging();
					this._Date_of_Birth = value;
					this.SendPropertyChanged("Date_of_Birth");
					this.OnDate_of_BirthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="NVarChar(50)")]
		public string Gender
		{
			get
			{
				return this._Gender;
			}
			set
			{
				if ((this._Gender != value))
				{
					this.OnGenderChanging(value);
					this.SendPropertyChanging();
					this._Gender = value;
					this.SendPropertyChanged("Gender");
					this.OnGenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(500)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nationality", DbType="NVarChar(50)")]
		public string Nationality
		{
			get
			{
				return this._Nationality;
			}
			set
			{
				if ((this._Nationality != value))
				{
					this.OnNationalityChanging(value);
					this.SendPropertyChanging();
					this._Nationality = value;
					this.SendPropertyChanged("Nationality");
					this.OnNationalityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Complain_Against", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Complain_Against
		{
			get
			{
				return this._Complain_Against;
			}
			set
			{
				if ((this._Complain_Against != value))
				{
					this.OnComplain_AgainstChanging(value);
					this.SendPropertyChanging();
					this._Complain_Against = value;
					this.SendPropertyChanged("Complain_Against");
					this.OnComplain_AgainstChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Suspect_Id", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Suspect_Id
		{
			get
			{
				return this._Suspect_Id;
			}
			set
			{
				if ((this._Suspect_Id != value))
				{
					this.OnSuspect_IdChanging(value);
					this.SendPropertyChanging();
					this._Suspect_Id = value;
					this.SendPropertyChanged("Suspect_Id");
					this.OnSuspect_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Details", DbType="NVarChar(1024)")]
		public string Details
		{
			get
			{
				return this._Details;
			}
			set
			{
				if ((this._Details != value))
				{
					this.OnDetailsChanging(value);
					this.SendPropertyChanging();
					this._Details = value;
					this.SendPropertyChanged("Details");
					this.OnDetailsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Complain_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Complain_date
		{
			get
			{
				return this._Complain_date;
			}
			set
			{
				if ((this._Complain_date != value))
				{
					this.OnComplain_dateChanging(value);
					this.SendPropertyChanging();
					this._Complain_date = value;
					this.SendPropertyChanged("Complain_date");
					this.OnComplain_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Creation_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Creation_Date
		{
			get
			{
				return this._Creation_Date;
			}
			set
			{
				if ((this._Creation_Date != value))
				{
					this.OnCreation_DateChanging(value);
					this.SendPropertyChanging();
					this._Creation_Date = value;
					this.SendPropertyChanged("Creation_Date");
					this.OnCreation_DateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Criminal")]
	public partial class Criminal : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Criminal_id;
		
		private string _National_Id;
		
		private System.Nullable<System.DateTime> _Date_of_Birth;
		
		private string _Gender;
		
		private string _Address;
		
		private string _Image;
		
		private string _Job;
		
		private string _Nationality;
		
		private string _Detention_Status;
		
		private System.Nullable<System.DateTime> _Detention_Date;
		
		private System.Nullable<System.DateTime> _Creation_Date;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnCriminal_idChanging(string value);
    partial void OnCriminal_idChanged();
    partial void OnNational_IdChanging(string value);
    partial void OnNational_IdChanged();
    partial void OnDate_of_BirthChanging(System.Nullable<System.DateTime> value);
    partial void OnDate_of_BirthChanged();
    partial void OnGenderChanging(string value);
    partial void OnGenderChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnImageChanging(string value);
    partial void OnImageChanged();
    partial void OnJobChanging(string value);
    partial void OnJobChanged();
    partial void OnNationalityChanging(string value);
    partial void OnNationalityChanged();
    partial void OnDetention_StatusChanging(string value);
    partial void OnDetention_StatusChanged();
    partial void OnDetention_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnDetention_DateChanged();
    partial void OnCreation_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreation_DateChanged();
    #endregion
		
		public Criminal()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Criminal_id", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Criminal_id
		{
			get
			{
				return this._Criminal_id;
			}
			set
			{
				if ((this._Criminal_id != value))
				{
					this.OnCriminal_idChanging(value);
					this.SendPropertyChanging();
					this._Criminal_id = value;
					this.SendPropertyChanged("Criminal_id");
					this.OnCriminal_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_National_Id", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string National_Id
		{
			get
			{
				return this._National_Id;
			}
			set
			{
				if ((this._National_Id != value))
				{
					this.OnNational_IdChanging(value);
					this.SendPropertyChanging();
					this._National_Id = value;
					this.SendPropertyChanged("National_Id");
					this.OnNational_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date_of_Birth", DbType="DateTime")]
		public System.Nullable<System.DateTime> Date_of_Birth
		{
			get
			{
				return this._Date_of_Birth;
			}
			set
			{
				if ((this._Date_of_Birth != value))
				{
					this.OnDate_of_BirthChanging(value);
					this.SendPropertyChanging();
					this._Date_of_Birth = value;
					this.SendPropertyChanged("Date_of_Birth");
					this.OnDate_of_BirthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="NVarChar(50)")]
		public string Gender
		{
			get
			{
				return this._Gender;
			}
			set
			{
				if ((this._Gender != value))
				{
					this.OnGenderChanging(value);
					this.SendPropertyChanging();
					this._Gender = value;
					this.SendPropertyChanged("Gender");
					this.OnGenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(500)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Image", DbType="NVarChar(250)")]
		public string Image
		{
			get
			{
				return this._Image;
			}
			set
			{
				if ((this._Image != value))
				{
					this.OnImageChanging(value);
					this.SendPropertyChanging();
					this._Image = value;
					this.SendPropertyChanged("Image");
					this.OnImageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Job", DbType="NVarChar(50)")]
		public string Job
		{
			get
			{
				return this._Job;
			}
			set
			{
				if ((this._Job != value))
				{
					this.OnJobChanging(value);
					this.SendPropertyChanging();
					this._Job = value;
					this.SendPropertyChanged("Job");
					this.OnJobChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nationality", DbType="NVarChar(50)")]
		public string Nationality
		{
			get
			{
				return this._Nationality;
			}
			set
			{
				if ((this._Nationality != value))
				{
					this.OnNationalityChanging(value);
					this.SendPropertyChanging();
					this._Nationality = value;
					this.SendPropertyChanged("Nationality");
					this.OnNationalityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Detention_Status", DbType="NVarChar(50)")]
		public string Detention_Status
		{
			get
			{
				return this._Detention_Status;
			}
			set
			{
				if ((this._Detention_Status != value))
				{
					this.OnDetention_StatusChanging(value);
					this.SendPropertyChanging();
					this._Detention_Status = value;
					this.SendPropertyChanged("Detention_Status");
					this.OnDetention_StatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Detention_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Detention_Date
		{
			get
			{
				return this._Detention_Date;
			}
			set
			{
				if ((this._Detention_Date != value))
				{
					this.OnDetention_DateChanging(value);
					this.SendPropertyChanging();
					this._Detention_Date = value;
					this.SendPropertyChanged("Detention_Date");
					this.OnDetention_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Creation_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Creation_Date
		{
			get
			{
				return this._Creation_Date;
			}
			set
			{
				if ((this._Creation_Date != value))
				{
					this.OnCreation_DateChanging(value);
					this.SendPropertyChanging();
					this._Creation_Date = value;
					this.SendPropertyChanged("Creation_Date");
					this.OnCreation_DateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Post_Mortem_Report")]
	public partial class Post_Mortem_Report : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Victims_Name;
		
		private string _Case_Id;
		
		private string _Officer_Id;
		
		private string _Gender;
		
		private System.Nullable<System.DateTime> _Date_of_Birth;
		
		private string _Address;
		
		private string _Nationality;
		
		private string _Doctor_Name;
		
		private string _Autospy;
		
		private string _Description;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnVictims_NameChanging(string value);
    partial void OnVictims_NameChanged();
    partial void OnCase_IdChanging(string value);
    partial void OnCase_IdChanged();
    partial void OnOfficer_IdChanging(string value);
    partial void OnOfficer_IdChanged();
    partial void OnGenderChanging(string value);
    partial void OnGenderChanged();
    partial void OnDate_of_BirthChanging(System.Nullable<System.DateTime> value);
    partial void OnDate_of_BirthChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnNationalityChanging(string value);
    partial void OnNationalityChanged();
    partial void OnDoctor_NameChanging(string value);
    partial void OnDoctor_NameChanged();
    partial void OnAutospyChanging(string value);
    partial void OnAutospyChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    #endregion
		
		public Post_Mortem_Report()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Victims_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Victims_Name
		{
			get
			{
				return this._Victims_Name;
			}
			set
			{
				if ((this._Victims_Name != value))
				{
					this.OnVictims_NameChanging(value);
					this.SendPropertyChanging();
					this._Victims_Name = value;
					this.SendPropertyChanged("Victims_Name");
					this.OnVictims_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Case_Id", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Case_Id
		{
			get
			{
				return this._Case_Id;
			}
			set
			{
				if ((this._Case_Id != value))
				{
					this.OnCase_IdChanging(value);
					this.SendPropertyChanging();
					this._Case_Id = value;
					this.SendPropertyChanged("Case_Id");
					this.OnCase_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Officer_Id", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Officer_Id
		{
			get
			{
				return this._Officer_Id;
			}
			set
			{
				if ((this._Officer_Id != value))
				{
					this.OnOfficer_IdChanging(value);
					this.SendPropertyChanging();
					this._Officer_Id = value;
					this.SendPropertyChanged("Officer_Id");
					this.OnOfficer_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="NVarChar(50)")]
		public string Gender
		{
			get
			{
				return this._Gender;
			}
			set
			{
				if ((this._Gender != value))
				{
					this.OnGenderChanging(value);
					this.SendPropertyChanging();
					this._Gender = value;
					this.SendPropertyChanged("Gender");
					this.OnGenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date_of_Birth", DbType="DateTime")]
		public System.Nullable<System.DateTime> Date_of_Birth
		{
			get
			{
				return this._Date_of_Birth;
			}
			set
			{
				if ((this._Date_of_Birth != value))
				{
					this.OnDate_of_BirthChanging(value);
					this.SendPropertyChanging();
					this._Date_of_Birth = value;
					this.SendPropertyChanged("Date_of_Birth");
					this.OnDate_of_BirthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(500)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nationality", DbType="NVarChar(50)")]
		public string Nationality
		{
			get
			{
				return this._Nationality;
			}
			set
			{
				if ((this._Nationality != value))
				{
					this.OnNationalityChanging(value);
					this.SendPropertyChanging();
					this._Nationality = value;
					this.SendPropertyChanged("Nationality");
					this.OnNationalityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Doctor_Name", DbType="NVarChar(50)")]
		public string Doctor_Name
		{
			get
			{
				return this._Doctor_Name;
			}
			set
			{
				if ((this._Doctor_Name != value))
				{
					this.OnDoctor_NameChanging(value);
					this.SendPropertyChanging();
					this._Doctor_Name = value;
					this.SendPropertyChanged("Doctor_Name");
					this.OnDoctor_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Autospy", DbType="NVarChar(250)")]
		public string Autospy
		{
			get
			{
				return this._Autospy;
			}
			set
			{
				if ((this._Autospy != value))
				{
					this.OnAutospyChanging(value);
					this.SendPropertyChanging();
					this._Autospy = value;
					this.SendPropertyChanged("Autospy");
					this.OnAutospyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(500)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Employee")]
	public partial class Employee : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Full_Name;
		
		private string _User_Id;
		
		private string _Password;
		
		private System.Nullable<System.DateTime> _Date_of_Birth;
		
		private string _Gender;
		
		private string _Work_place;
		
		private string _Address;
		
		private string _Phone_number;
		
		private string _Designation;
		
		private string _Image;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFull_NameChanging(string value);
    partial void OnFull_NameChanged();
    partial void OnUser_IdChanging(string value);
    partial void OnUser_IdChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnDate_of_BirthChanging(System.Nullable<System.DateTime> value);
    partial void OnDate_of_BirthChanged();
    partial void OnGenderChanging(string value);
    partial void OnGenderChanged();
    partial void OnWork_placeChanging(string value);
    partial void OnWork_placeChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnPhone_numberChanging(string value);
    partial void OnPhone_numberChanged();
    partial void OnDesignationChanging(string value);
    partial void OnDesignationChanged();
    partial void OnImageChanging(string value);
    partial void OnImageChanged();
    #endregion
		
		public Employee()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Full_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Full_Name
		{
			get
			{
				return this._Full_Name;
			}
			set
			{
				if ((this._Full_Name != value))
				{
					this.OnFull_NameChanging(value);
					this.SendPropertyChanging();
					this._Full_Name = value;
					this.SendPropertyChanged("Full_Name");
					this.OnFull_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Id", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string User_Id
		{
			get
			{
				return this._User_Id;
			}
			set
			{
				if ((this._User_Id != value))
				{
					this.OnUser_IdChanging(value);
					this.SendPropertyChanging();
					this._User_Id = value;
					this.SendPropertyChanged("User_Id");
					this.OnUser_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date_of_Birth", DbType="DateTime")]
		public System.Nullable<System.DateTime> Date_of_Birth
		{
			get
			{
				return this._Date_of_Birth;
			}
			set
			{
				if ((this._Date_of_Birth != value))
				{
					this.OnDate_of_BirthChanging(value);
					this.SendPropertyChanging();
					this._Date_of_Birth = value;
					this.SendPropertyChanged("Date_of_Birth");
					this.OnDate_of_BirthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="NVarChar(50)")]
		public string Gender
		{
			get
			{
				return this._Gender;
			}
			set
			{
				if ((this._Gender != value))
				{
					this.OnGenderChanging(value);
					this.SendPropertyChanging();
					this._Gender = value;
					this.SendPropertyChanged("Gender");
					this.OnGenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Work_place", DbType="NVarChar(50)")]
		public string Work_place
		{
			get
			{
				return this._Work_place;
			}
			set
			{
				if ((this._Work_place != value))
				{
					this.OnWork_placeChanging(value);
					this.SendPropertyChanging();
					this._Work_place = value;
					this.SendPropertyChanged("Work_place");
					this.OnWork_placeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(500)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone_number", DbType="NVarChar(50)")]
		public string Phone_number
		{
			get
			{
				return this._Phone_number;
			}
			set
			{
				if ((this._Phone_number != value))
				{
					this.OnPhone_numberChanging(value);
					this.SendPropertyChanging();
					this._Phone_number = value;
					this.SendPropertyChanged("Phone_number");
					this.OnPhone_numberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Designation", DbType="NVarChar(50)")]
		public string Designation
		{
			get
			{
				return this._Designation;
			}
			set
			{
				if ((this._Designation != value))
				{
					this.OnDesignationChanging(value);
					this.SendPropertyChanging();
					this._Designation = value;
					this.SendPropertyChanged("Designation");
					this.OnDesignationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Image", DbType="NVarChar(250)")]
		public string Image
		{
			get
			{
				return this._Image;
			}
			set
			{
				if ((this._Image != value))
				{
					this.OnImageChanging(value);
					this.SendPropertyChanging();
					this._Image = value;
					this.SendPropertyChanged("Image");
					this.OnImageChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
